name: marathon-envs
channels:
  - pytorch
dependencies:
  - pip
  - pytorch 
  - torchvision 
  - torchaudio 
  # - cudatoolkit=10.2
  - numpy
  - pip:
     - mlagents==0.26     #- corresponds to mlagents 1.8 in C#

