behaviors:
    default:
        trainer_type: ppo
        hyperparameters:
            batch_size: 1024
            beta: 5.0e-3
            buffer_size: 10240
            epsilon: 0.2
            lambd: 0.95
            learning_rate: 3.0e-4
            num_epoch: 3
        network_settings:
            normalize: false
            num_layers: 2
            hidden_units: 128
            vis_encode_type: simple
            # memory:
            #     memory_size: 256
            #     sequence_length: 64
        reward_signals: 
            extrinsic:
                strength: 1.0
                gamma: 0.99
        max_steps: 5.0e4
        time_horizon: 64
        threaded: true
        summary_freq: 1000


    MarCon-v0:
        trainer_type: ppo
        hyperparameters:
            num_epoch: 3
            beta: 9e-3
            learning_rate: 1e-4
            batch_size: 2048 
            buffer_size: 20480 # 768 * 4
        summary_freq: 100000
        checkpoint_interval: 5000000
        network_settings:
            num_layers: 2
            hidden_units: 512    
            normalize: true
        max_steps: 300e6
        time_horizon: 1000
