behaviors:
  default:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      beta: 5.0e-3
      buffer_size: 10240
      epsilon: 0.2
      lambd: 0.95
      learning_rate: 3.0e-4
      num_epoch: 3
    network_settings:
      normalize: false
      num_layers: 2
      hidden_units: 128
      vis_encode_type: simple
      # memory:
      #     memory_size: 256
      #     sequence_length: 64
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
    max_steps: 5.0e4
    time_horizon: 64
    threaded: true
    summary_freq: 1000

  MarathonManBackflip-v0:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 3
      beta: .00001
      learning_rate: 1e-4
      batch_size: 768
      buffer_size: 21504 # 768 * 28
    time_horizon: 100
    summary_freq: 100000
    network_settings:
      num_layers: 2
      normalize: true
      hidden_units: 256
    max_steps: 128e6
    threaded: true

  MarathonManSlash-v0:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 3
      beta: .00001
      epsilon: 0.2
      lambd: 0.95
      learning_rate: 1e-4
      batch_size: 768
      buffer_size: 21504 # 768 * 28
    time_horizon: 100
    summary_freq: 100000
    network_settings:
      num_layers: 2
      normalize: true
      hidden_units: 512
    max_steps: 128e6
    threaded: true

  MarathonManWalking-v0:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 3
      beta: .00001
      learning_rate: 1e-4
      batch_size: 768
      buffer_size: 21504 # 768 * 28
    time_horizon: 100
    summary_freq: 100000
    network_settings:
      num_layers: 2
      normalize: true
      hidden_units: 256
    max_steps: 64e6
    threaded: true

  MarathonManRunning-v0:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 3
      beta: .00001
      learning_rate: 1e-4
      batch_size: 768
      buffer_size: 21504 # 768 * 28
    time_horizon: 100
    summary_freq: 100000
    network_settings:
      num_layers: 2
      normalize: true
      hidden_units: 256
    max_steps: 64e6
    threaded: true

  MarathonManJazzDancing-v0:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 3
      beta: .00001
      learning_rate: 1e-4
      batch_size: 768
      buffer_size: 21504 # 768 * 28
    time_horizon: 100
    summary_freq: 100000
    network_settings:
      num_layers: 2
      normalize: true
      hidden_units: 256
    max_steps: 64e6
    threaded: true

  MarathonManMMAKick-v0:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 3
      beta: .00001
      learning_rate: 1e-4
      batch_size: 768
      buffer_size: 21504 # 768 * 28
    time_horizon: 100
    summary_freq: 100000
    network_settings:
      num_layers: 2
      normalize: true
      hidden_units: 256
    max_steps: 64e6
    threaded: true

  MarathonManPunchingBag-v0:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 3
      beta: .00001
      learning_rate: 1e-4
      batch_size: 768
      buffer_size: 21504 # 768 * 28
    time_horizon: 100
    summary_freq: 100000
    network_settings:
      num_layers: 2
      normalize: true
      hidden_units: 256
    max_steps: 64e6
    threaded: true

  MarathonMan-v0:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 3
      beta: .003
      learning_rate: 3e-4
      batch_size: 1024
      buffer_size: 8196
    time_horizon: 1000
    summary_freq: 25000
    network_settings:
      num_layers: 3
      normalize: true
      hidden_units: 512
    max_steps: 5.e6
    threaded: true

  MarathonManSparse-v0:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 3
      beta: .003
      learning_rate: 3e-4
      batch_size: 64
      buffer_size: 640
    time_horizon: 1000
    summary_freq: 25000
    network_settings:
      num_layers: 2
      normalize: true
      hidden_units: 512
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.9999
    max_steps: 5.e6
    threaded: true

  Hopper-v0:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 10
      beta: .003
      learning_rate: 1e-3
      batch_size: 16
      buffer_size: 5120
    time_horizon: 100
    summary_freq: 10000
    network_settings:
      num_layers: 2
      normalize: false
      hidden_units: 64
    max_steps: 1e6
    threaded: true

  Walker2d-v0:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 10
      beta: .003
      learning_rate: 1e-3
      batch_size: 16
      buffer_size: 5120
    time_horizon: 100
    summary_freq: 10000
    network_settings:
      num_layers: 2
      normalize: false
      hidden_units: 64
    max_steps: 1e6
    threaded: true

  Ant-v0:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 10
      beta: .003
      learning_rate: 1e-3
      batch_size: 32
      buffer_size: 5120
    time_horizon: 100
    summary_freq: 10000
    network_settings:
      num_layers: 2
      normalize: false
      hidden_units: 64
    max_steps: 1e6
    threaded: true

  TerrainHopper-v0:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 3
      beta: 2e-2
      learning_rate: 3e-4
      batch_size: 768
      buffer_size: 3072
    time_horizon: 1000
    summary_freq: 50000
    network_settings:
      num_layers: 2
      normalize: false
      hidden_units: 64
    max_steps: 50e6
    threaded: true

  TerrainWalker2d-v0:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 3
      beta: 2e-2
      learning_rate: 3e-4
      batch_size: 768
      buffer_size: 3072
    time_horizon: 1000
    summary_freq: 50000
    network_settings:
      num_layers: 2
      normalize: false
      hidden_units: 64
    max_steps: 50e6
    threaded: true

  TerrainAnt-v0:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 3
      beta: 2e-2
      learning_rate: 3e-4
      batch_size: 768
      buffer_size: 3072
    time_horizon: 1000
    summary_freq: 50000
    network_settings:
      num_layers: 2
      normalize: false
      hidden_units: 64
    max_steps: 50e6
    threaded: true

  TerrainMarathonMan-v0:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 3
      beta: 2e-2
      learning_rate: 3e-4
      batch_size: 768
      buffer_size: 3072
    time_horizon: 1000
    summary_freq: 50000
    network_settings:
      num_layers: 2
      normalize: false
      hidden_units: 64
    max_steps: 50e6
    threaded: true

  DReCon-v0:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 3
      beta: 9e-3
      learning_rate: 1e-4
      batch_size: 2048
      buffer_size: 20480 # 768 * 4
    summary_freq: 100000
    checkpoint_interval: 5000000
    network_settings:
      num_layers: 2
      hidden_units: 512
      normalize: true
    max_steps: 128e6
    time_horizon: 1000

  SambaCon-v1:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 3
      beta: 9e-3
      learning_rate: 1e-4
      batch_size: 2048
      buffer_size: 20480 # 768 * 4
    summary_freq: 100000
    checkpoint_interval: 5000000
    network_settings:
      num_layers: 2
      hidden_units: 512
      normalize: true
    max_steps: 128e6
    time_horizon: 1000

  MarCon-v0:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 3
      beta: 9e-3
      learning_rate: 1e-4
      batch_size: 2048
      buffer_size: 20480 # 768 * 4
    summary_freq: 100000
    checkpoint_interval: 5000000
    network_settings:
      num_layers: 2
      hidden_units: 512
      normalize: true
    max_steps: 128e6
    time_horizon: 1000

  DReConMocap-v0:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 3
      beta: 2e-2
      learning_rate: 1e-4
      batch_size: 768
      buffer_size: 3072
      # batch_size: 2048
      # buffer_size: 20480 # 768 * 4
    summary_freq: 100000
    checkpoint_interval: 5000000
    network_settings:
      num_layers: 2
      hidden_units: 256
      normalize: true
    max_steps: 128e6
    time_horizon: 1000

  MarConMocap-v0:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 3
      beta: 2e-2
      learning_rate: 1e-4
      batch_size: 768
      buffer_size: 3072
      # batch_size: 2048
      # buffer_size: 20480 # 768 * 4
    summary_freq: 100000
    checkpoint_interval: 5000000
    network_settings:
      num_layers: 2
      hidden_units: 256
      normalize: true
    max_steps: 128e6
    time_horizon: 1000

  MarConQuadruped-v0:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 3
      beta: 2e-2
      learning_rate: 1e-4
      batch_size: 768
      # buffer_size: 21504 # 768 * 28
      buffer_size: 3072 # 768 * 4
    summary_freq: 100000
    checkpoint_interval: 5000000
    network_settings:
      num_layers: 2
      hidden_units: 256
      normalize: true
    max_steps: 128e6
    time_horizon: 1000

  MotionDReCon-v0:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 3
      beta: 9e-3
      learning_rate: 1e-4
      batch_size: 2048
      buffer_size: 20480 # 768 * 4
    summary_freq: 100000
    checkpoint_interval: 5000000
    network_settings:
      num_layers: 2
      hidden_units: 512
      normalize: true
    max_steps: 128e6
    time_horizon: 1000

  MotionMarCon-v0:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 3
      beta: 9e-3
      learning_rate: 1e-4
      batch_size: 2048
      buffer_size: 20480 # 768 * 4
    summary_freq: 100000
    checkpoint_interval: 5000000
    network_settings:
      num_layers: 2
      hidden_units: 512
      normalize: true
    max_steps: 128e6
    time_horizon: 1000
