behaviors:
  default:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      beta: 5.0e-3
      buffer_size: 10240
      epsilon: 0.2
      lambd: 0.95
      learning_rate: 3.0e-4
      num_epoch: 3
    network_settings:
      normalize: false
      num_layers: 2
      hidden_units: 128
      vis_encode_type: simple
      # memory:
      #     memory_size: 256
      #     sequence_length: 64
    reward_signals: 
      extrinsic:
        strength: 1.0
        gamma: 0.99
    max_steps: 5.0e4
    time_horizon: 64
    threaded: true
    summary_freq: 1000

  MarCon-v0:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0001
      beta: 0.009
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
      memory: null
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 5000000
    max_steps: 128000000
    # max_steps: 300000000
    time_horizon: 1000
    summary_freq: 100000
    threaded: true
    self_play: null
    behavioral_cloning: null

env_settings:
  env_args:
  - --spawn-env=MarConHumanoid-v0
  - --num-spawn-envs=20
  base_port: 5005
  num_envs: 25
engine_settings:
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true
debug: false
